from django.urls import path
from PhoenixApp import views

urlpatterns = [
    path('', views.index, name="index"),
    path('home', views.home, name="home"),
    path('clubs', views.clubs, name="clubs"),
    path('events', views.events, name="events"),
    path('blogs', views.blogs, name="blogs"),
    path('gallery', views.gallery, name="gallery"),
    path('webteam', views.webteam, name="webteam"),
    path('core2020-21', views.core2020_21, name="core2020_21"),
    path('contact', views.contact, name="contact"),
    path('avenir', views.avenir, name="avenir"),
    path('brainstormer', views.brainstormer, name="brainstormer"),
    path('aavahan', views.aavahan, name="aavahan"),
    path('cybernix', views.cybernix, name="cybernix"),
    path('eloquense', views.eloquense, name="eloquense"),
    path('robonix', views.robonix, name="robonix"),
    path('lensified', views.lensified, name="lensified"),
    path('nirmaan', views.nirmaan, name="nirmaan"),
    path('review', views.review, name="review"),
    path('<str:slug>/result', views.result, name="result"),
    path('membership', views.membership, name="membership"),
    path('blogs/<int:myid>', views.blog, name="blog"),
    path('create_card', views.create_card, name="create_card"),
    path('git_mail', views.git_mail, name="git_mail"),
    # path('events/Creativarty', views.Creativarty, name="Creativarty"),
    # path('events/Creativarty/confirmation/', views.Confirmation, name="Confirmation"),
    # path('events/Quizomania', views.Quizomania, name="Quizomania"),
    #path('events/Quizomania/confirmation/', views.confirmation, name="confirmation"),
    path('events/git-learning-version-control', views.git, name="git"),
    # path('events/git-learning-version-control/confirmation/',
    #      views.confirmation, name="confirmation"),
    # path('events/choose-a-tech-field', views.chooseATechField, name="choose-a-tech-field"),
    # path('events/choose-a-tech-field/confirmation/', views.confirmation, name="confirmation"),
    # path('events/getting-started-with-competitive-coding', views.gswcp, name="getting-started-with-competitive-coding"),
    # path('events/getting-started-with-competitive-coding/confirmation/', views.confirmation, name="confirmation"),
    # path('events/getting-started-with-technical-content-writing', views.gswcwv, name="getting-started-with-technical-content-writing"),
    # path('events/getting-started-with-technical-content-writing/confirmation/', views.confirmation, name="confirmation"),
    # path('events/robonix-bootcamp-registration', views.robonixintro, name="robonix-bootcamp-registration"),
    # path('events/robonix-bootcamp-registration/confirmation/', views.robonixintroconfirmation, name="confirmation"),
    # path('events/introduction-to-app-development', views.iad, name="introduction-to-app-development"),
    # path('events/introduction-to-app-development/confirmation/', views.iadconfirmation, name="confirmation"),
    # path('events/introduction-to-web-development', views.iwd, name="introduction-to-web-development"),
    # path('events/introduction-to-web-development/confirmation/', views.iwdconfirmation, name="confirmation"),
    # path('events/introduction-to-python-and-django', views.ipd, name="introduction-to-python-and-django"),
    # path('events/introduction-to-python-and-django/confirmation/', views.ipdconfirmation, name="confirmation"),
    # path('events/getting-started-with-backend-development', views.gswbd, name="getting-started-with-backend-development"),
    # path('events/getting-started-with-backend-development/confirmation/', views.gswbdconfirmation, name="confirmation"),
    path('events/an-advanced-workshop-in-backend-development', views.aawibd, name="an-advanced-workshop-in-backend-development"),
    path('events/an-advanced-workshop-in-backend-development/confirmation/', views.aawibdconfirmation, name="confirmation"),

]
