# Generated by Django 3.2.9 on 2021-12-11 17:15

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=250)),
                ('department', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('image', models.FileField(upload_to='Creativarty/')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogTitle', models.CharField(default='', max_length=80)),
                ('Studentname', models.CharField(default='', max_length=50)),
                ('aboutstudent', models.CharField(default='', max_length=500)),
                ('Date', models.CharField(default='', max_length=20)),
                ('Content', models.TextField()),
                ('image', models.ImageField(default='', upload_to='blogs/blog/images')),
                ('studentimage', models.ImageField(default='', upload_to='blogs/student/images')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.FileField(upload_to='Membership/Card/')),
                ('font', models.FileField(upload_to='Membership/Font/')),
            ],
        ),
        migrations.CreateModel(
            name='ChooseATechField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=100)),
                ('session', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('year', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(default='', max_length=80)),
                ('Event_id', models.CharField(default='', max_length=80)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Git',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=100)),
                ('git', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='gswcpM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=100)),
                ('session', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Getting Started with Competitive Coding',
            },
        ),
        migrations.CreateModel(
            name='gswcw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=100)),
                ('session', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Getting Started with Technical Content Writing',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('email', models.CharField(default='', max_length=150)),
                ('session', models.CharField(default='', max_length=150)),
                ('department', models.CharField(default='', max_length=120)),
                ('contact', models.CharField(default='', max_length=20)),
                ('transaction_id', models.CharField(default='', max_length=30)),
                ('transaction_receipt', models.FileField(upload_to='Membership/Receipt/')),
                ('image', models.FileField(upload_to='Membership/Images/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PreviousEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='quizomania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='robonixIntro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=100)),
                ('session', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Robonix Bootcamp Registration Form',
            },
        ),
        migrations.CreateModel(
            name='UpComingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('desc', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('image', models.ImageField(default='', upload_to='upcomingevents/images')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='eventname')),
                ('studentname', models.CharField(default='', max_length=60)),
                ('position', models.CharField(default='', max_length=10)),
                ('year', models.CharField(default='', max_length=10)),
                ('department', models.CharField(default='', max_length=50)),
                ('college', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='result/images')),
                ('eventname', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PhoenixApp.previousevent')),
            ],
        ),
    ]
