# Generated by Django 3.2.9 on 2021-12-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoenixApp', '0002_previousevent_is_for_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='appDevelopment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=100)),
                ('session', models.CharField(default='', max_length=100)),
                ('prior', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Introduction to App Development',
            },
        ),
    ]
